'use strict';
const $=id=>document.getElementById(id);let state=null,busy=false,exported=null,replay=null,snapshot=null,cursor=[0,0],startedAt=null,elapsed=0;
const directions={up:[-1,0],down:[1,0],left:[0,-1],right:[0,1],wait:[0,0]};
function toast(s){$('toast').textContent=s;$('toast').hidden=false;setTimeout(()=>{$('toast').hidden=true},4000)}
async function api(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const j=await r.json();if(!r.ok)throw Error(j.error||r.status);return j}
function payload(extra={}){return{epoch:state.epoch,revision:state.observation.revision,...extra}}
const arenaChoices=[['human','你 · 键盘与鼠标'],['B3','B3 · 生存与效率'],['L3','L3 · 本地生存小模型'],['B2','B2 · 原对手感知'],['L_v2','L2 · 原大棋盘模型'],['B1','B1 · 风险感知'],['B0','B0 · 随机'],['E','E · 参数探索（16×16）'],['L','L1 · 原9×9模型']];
const raceChoices=[['human','你 · 手动揭格'],['R0','R0 · 随机揭格'],['R1','R1 · 概率与线索'],['C1','C1 · 本地经典小模型']];
function populatePolicies(mode,values){const choices=mode==='classic_race'?raceChoices:mode==='classic'?[['human','手动经典模式']]:arenaChoices;for(let i=0;i<2;i++){const select=$('p'+i),previous=values?.[i]||select.value;select.replaceChildren();for(const [value,label] of choices){const option=document.createElement('option');option.value=value;option.textContent=label;select.append(option)}select.value=choices.some(x=>x[0]===previous)?previous:(i===0?'human':mode==='classic_race'?'R1':mode==='classic'?'human':'B3');select.disabled=mode==='classic'}$('watchBattle').textContent=mode==='classic_race'?'观看经典 AI 对打 · R1 vs C1':'观看争夺 AI 对打 · B3 vs L3'}
function syncSelectors(){$('mode').value=state.mode;populatePolicies(state.mode,state.controllers);$('difficulty').value=state.observation.preset||'legacy';$('scoring').value=state.observation.scoring||'diamonds';presetHint()}

function dimensions(o){return[o.height||o.size,o.width||o.size]}
function presetHint(){const p=$('difficulty').value,mode=$('mode').value,old=['legacy','beginner'].includes(p);$('scoringLabel').hidden=mode!=='arena';$('scoring').disabled=old;if(old)$('scoring').value='diamonds';$('presetHint').textContent=mode==='classic_race'?'同一基础雷图、同一中心首击，各自独立揭格。先比通关，再比安全格和行动数；C1仅在9×9训练。':mode==='classic'?(p==='legacy'?'原始规则验证：首击可能踩雷。':'数字为周围八格雷数；首击安全、插旗与数字连开。'):(old?'原始实验 v1 · 3钻石 · 每人1生命':`${p==='expert'?'30×16 · 11钻石 · 1600':'16×16 · 7钻石 · 800'}步 · 每人3生命。`+($('scoring').value==='survival-v1'?'v3：钻石优先，保命与行动效率次之。':'v2：仅比较钻石。'));}
function startClock(){if(startedAt===null&&!replay&&!state.observation.done)startedAt=Date.now()-elapsed*1000}
function chord(r,c){return command('/api/chord',{r,c})}
async function idle(){while(busy)await new Promise(resolve=>setTimeout(resolve,10))}
async function command(path,extra={}){if(busy||replay)return;busy=true;try{state=await api(path,payload(extra));if(path==='/api/restore')syncSelectors();render()}catch(e){toast(e.message)}finally{busy=false}}
function cellClick(r,c){if(!state||replay)return;let o=state.observation;if(state.mode==='classic_race'){cursor=[r,c];return command('/api/action',{r,c})}if(state.mode==='classic'){cursor=[r,c];startClock();const n=o.revealed.find(x=>x[0]===r&&x[1]===c)?.[2];return n>0?chord(r,c):command('/api/action',{r,c})}const [pr,pc]=o.positions[o.turn];let a=Object.keys(directions).find(a=>directions[a][0]===r-pr&&directions[a][1]===c-pc);if(a)command('/api/action',{action:a});else toast('每次只能上下左右移动一格。')}
function inputAction(action){
 if(!state||replay)return;
 if(!['classic','classic_race'].includes(state.mode))return command('/api/action',{action});
 if(action==='wait')return cellClick(...cursor);
 const [h,w]=dimensions(state.observation),[dr,dc]=directions[action];cursor=[Math.max(0,Math.min(h-1,cursor[0]+dr)),Math.max(0,Math.min(w-1,cursor[1]+dc))];render();
}
function render(){if(!state)return;$('raceBoards').hidden=state.mode!=='classic_race';$('arenaConsole').hidden=state.mode==='classic_race';$('snapshot').disabled=state.mode!=='arena';if(state.mode==='classic_race'){renderRace();return}const o=state.observation,classic=state.mode==='classic';$('board').replaceChildren();const revealed=new Map(o.revealed.map(x=>[x[0]+','+x[1],x[2]]));const diamonds=new Set((o.diamonds||[]).map(x=>x.join(','))), flags=new Set((classic?(o.flags||[]):state.flags||[]).map(x=>x.join(',')));const decision=state.decision;const [height,width]=dimensions(o);$('board').style.gridTemplateColumns=`repeat(${width},var(--cell))`;$('board').dataset.width=width;$('board').classList.toggle('expert',width>20);$('boardSize').textContent=`${width} × ${height}`;$('boardSpec').textContent=`${o.mine_count} 颗雷`+(classic?' · 揭开全部安全格':` · ${o.resource_count||3} 颗钻石 · 2 位玩家`);$('rulesBadge').textContent=o.rule_version;$('mineCounter').textContent=String(o.mine_count-flags.size).padStart(3,'0');$('clockLabel').textContent=classic?'秒 · 本地计时':'行动步数';$('clockCounter').textContent=String(classic?elapsed:o.steps).padStart(3,'0');$('faceReset').textContent=o.done?(o.winner==='win'?'☻':'☹'):'☺';if(o.done&&startedAt!==null){elapsed=Math.floor((Date.now()-startedAt)/1000);startedAt=null;}
for(let r=0;r<height;r++)for(let c=0;c<width;c++){const k=r+','+c,n=revealed.get(k),b=document.createElement('button');b.className='cell'+(n!==undefined?' revealed':'')+(diamonds.has(k)?' diamond':'')+(n===-1?' exploded':'');b.dataset.number=n;b.dataset.row=r;b.dataset.col=c;b.setAttribute('aria-label',`${r+1}行${c+1}列 ${n===-1?(classic?'地雷（终局揭示）':'已爆地雷'):n!==undefined?'数字'+n:diamonds.has(k)?'安全钻石':'未知'}`);let clue=document.createElement('span');clue.className='clue';clue.textContent=n===-1?'✹':n===undefined||n===0?'':n;b.append(clue);if(diamonds.has(k)){const gem=document.createElement('span');gem.className='resource-mark';gem.textContent='◆';b.append(gem)}if(flags.has(k)){let f=document.createElement('span');f.className='flag';f.textContent='⚑';b.append(f)}if(!classic)o.positions.forEach((p,i)=>{if(p[0]===r&&p[1]===c){b.classList.add('has-pawn');let pawn=document.createElement('span');pawn.className='pawn p'+i;pawn.textContent=(i?'B':'A')+(o.alive[i]?'':'×');b.append(pawn)}});if($('heat').checked&&decision?.risk&&n===undefined){let prob=decision.risk[r*o.size+c];if(Number.isFinite(prob)){let q=document.createElement('span');q.className='risk';q.textContent=Math.round(prob*100)+'%';b.append(q);b.style.boxShadow=`inset 0 0 18px rgba(200,85,50,${prob*.7})`}}b.onclick=()=>cellClick(r,c);b.oncontextmenu=e=>{e.preventDefault();command('/api/flag',{r,c})};b.ondblclick=e=>{if(classic){e.preventDefault();chord(r,c)}};if(classic&&r===cursor[0]&&c===cursor[1])b.classList.add('cursor');$('board').append(b)}
$('scoreDetail').textContent=o.scoring==='survival-v1'?`积分 = 100×钻石 + 10×剩余生命 − 本人行动/${o.max_steps}。A ${o.utility_scores[0].toFixed(3)} / B ${o.utility_scores[1].toFixed(3)}；行动 ${o.action_counts.join(' / ')}`:'';$('keyboardHint').textContent=classic?'方向键 / WASD 移动光标，空格揭格，F 插旗；左键揭格、右键插旗。点击已揭数字可连开（需相邻旗数匹配）。':'方向键 / WASD 移动，空格等待；也可点击相邻格。右键添加标记。';$('waitLabel').textContent=classic?'揭开光标格':'等待一回合';$('score0').textContent=classic?'—':o.scores[0];$('score1').textContent=classic?'—':o.scores[1];for(let i=0;i<2;i++)$('alive'+i).textContent=classic?'经典模式':o.alive[i]?(o.lives?`剩余 ${o.lives[i]} 次生命`:'可行动'):'已淘汰';$('turn').textContent=replay?'公开回放':o.done?'对局结束':classic?'经典扫雷':`轮到 ${o.turn?'B':'A'} · ${state.controllers[o.turn]}`;$('counter').textContent=classic?`${o.revealed.filter(x=>x[2]>=0).length} / ${height*width-o.mine_count} 安全格`:`${o.steps} / ${o.max_steps} 步`;
$('result').textContent=o.done?(classic?(o.won||o.winner==='win'?'全部安全格已揭开':'本局结束 · '+({mine:'踩雷',all_safe_revealed:'全部安全格已揭开'}[o.reason]||o.reason||o.winner||'踩雷')):(o.winner==='draw'?'平局':`玩家 ${o.winner===0?'A':'B'} 获胜`)+` · ${{diamonds_collected:'钻石取完',max_steps:'达到步数上限',all_eliminated:'双方停止行动',no_survivors:'双方均已淘汰'}[o.reason]||o.reason}`):state.paused?'已暂停 · 可用 AI 单步观察':classic?(o.first_click_safe?'左键揭格 · 右键插旗 · 首击安全':'原版验证规则 · 首击可能踩雷'):'先到钻石格得分 · 未知雷位保持隐藏';$('pause').textContent=state.paused?'继续':'暂停';$('diagnosis').hidden=!$('debug').checked;
$('diagnosis').replaceChildren();if(decision){const p=document.createElement('p');p.textContent=`${decision.policy} → ${decision.action} · ${decision.risk_status}`;$('diagnosis').append(p);const t=document.createElement('p');t.textContent=decision.target?`${decision.diagnostics?.target_kind?.startsWith('inferred_')?'动作推断目标（不是独立目标输出）':'规则策略明确目标'}：(${decision.target[0]+1}, ${decision.target[1]+1})。`:'此策略未显式输出目标。';$('diagnosis').append(t);const pre=document.createElement('pre');pre.textContent=JSON.stringify(decision.diagnostics||{},null,2);$('diagnosis').append(pre)}else $('diagnosis').textContent='AI 行动后显示其实际输出。热图对应最近一次决策前的公开状态。';$('rulesList').replaceChildren();const rules=classic?['揭开所有没有地雷的格子即可获胜。','右键插旗；数字表示周围八格的地雷数。','相邻旗数等于数字时，点击数字连开；插错旗会踩雷。']:[`上下左右移动一格，或等待；钻石先到先得，共 ${o.resource_count||3} 颗。`,o.lives?'踩雷扣一次生命并返回自己的起点；生命耗尽才停止行动。':'踩雷后停止行动，保留得分；另一方继续。',`钻石取完、双方淘汰或满 ${o.max_steps} 步结束。${o.scoring==='survival-v1'?'按钻石、剩余生命、较少本人行动依次比较。':'只比钻石数，同分平局。'}`];for(const text of rules){const li=document.createElement('li');li.textContent=text;$('rulesList').append(li)}$('rulesNote').textContent=classic?(o.first_click_safe?'经典模式首次揭格后才布雷，首击周围保证安全，零区自动展开。专家 30×16 / 99 雷，不保证每张图都无需猜测。':'原始经典验证模式固定雷位，首击不保证安全。'):(o.lives?(o.scoring==='survival-v1'?'挑战规则 v3：钻石、生命、行动分级计分；':'挑战规则 v2：')+'两角3×3起点区与钻石公开安全；零区展开。生命、复活和争夺为新增规则。':'原始实验 v1：起点与钻石保证安全，不展开零区，一次踩雷即淘汰。历史评测仅适用于此版本。');$('provenance').textContent=`来源：${state.source} · 公开观察，无隐藏雷图。`;$('replayControls').hidden=!replay;
}

function renderRace(){
 const o=state.observation,decision=state.decision;
 $('rulesBadge').textContent=o.rule_version;$('boardSize').textContent=`${o.width} × ${o.height}`;$('boardSpec').textContent=`${o.boards[0].mine_count} 雷 · 同图经典竞速`;
 $('scoreDetail').textContent='同图独立揭格 · 通关优先，其次安全格，最后比较更少主动揭格 · 计算时间仅作记录';
 for(let i=0;i<2;i++){
  const board=o.boards[i],result=o.results[i],el=$('raceBoard'+i),revealed=new Map(board.revealed.map(x=>[x[0]+','+x[1],x[2]]));el.replaceChildren();el.style.gridTemplateColumns=`repeat(${o.width},var(--cell))`;el.classList.toggle('expert',o.width>20);
  $('raceTitle'+i).textContent=`${i?'B':'A'} · ${state.controllers[i]}${!o.done&&o.turn===i?' · 当前行动':''}`;
  for(let r=0;r<o.height;r++)for(let c=0;c<o.width;c++){
   const n=revealed.get(r+','+c),b=document.createElement('button');b.className='cell'+(n!==undefined?' revealed':'')+(n===-1?' exploded':'');b.dataset.number=n;b.dataset.row=r;b.dataset.col=c;
   b.setAttribute('aria-label',`${i?'B':'A'}棋盘 ${r+1}行${c+1}列 ${n===-1?'已踩地雷':n===undefined?'未知':'数字'+n}`);
   const clue=document.createElement('span');clue.className='clue';clue.textContent=n===-1?'✹':n===undefined||n===0?'':n;b.append(clue);if($('heat').checked&&decision?.actor===i&&n===undefined&&Number.isFinite(decision.risk?.[r*o.width+c])){const q=document.createElement('span');q.className='risk';q.textContent=Math.round(decision.risk[r*o.width+c]*100)+'%';b.append(q)}
   if(!o.done&&i===o.turn&&r===cursor[0]&&c===cursor[1])b.classList.add('cursor');
   b.onclick=()=>{if(i!==o.turn||o.done)return;cellClick(r,c)};el.append(b);
  }
  $('score'+i).textContent=result.safe_revealed;$('alive'+i).textContent=result.done?(result.cleared?'全部安全格通关':'踩雷结束'):'仍在探索';
  $('raceStats'+i).textContent=`安全格 ${result.safe_revealed}/${o.width*o.height-board.mine_count} · 主动揭格 ${o.active_reveals[i]} · 累计决策 ${o.computation_seconds[i].toFixed(3)} 秒`;
 }
 $('turn').textContent=replay?'公开回放':o.done?'竞速结束':`轮到 ${o.turn?'B':'A'}`;$('counter').textContent=`累计 ${o.revision} 次主动揭格`;
 $('result').textContent=o.done?(o.winner==='draw'?'竞速平局':`玩家 ${o.winner?'B':'A'} 胜出`):state.paused?'已暂停 · 可单步观察':'两方在相同雷图上独立求解，共同首击已完成';
 $('pause').textContent=state.paused?'继续':'暂停';$('waitLabel').textContent='揭开光标格';$('keyboardHint').textContent='人工轮次可点当前棋盘的未知格，或方向键移动光标、空格揭格。AI只读取自己的棋盘；人工可见双板，人工场次不作公平竞速基准。';
 $('diagnosis').hidden=!$('debug').checked;$('diagnosis').replaceChildren();const pre=document.createElement('pre');pre.textContent=decision?JSON.stringify(decision.diagnostics||decision,null,2):'AI行动后显示公共风险、模型评分及真实计算依据。';$('diagnosis').append(pre);
 $('rulesList').replaceChildren();for(const text of ['两个棋盘的基础雷图、中心保护首击和难度相同。','轮流主动揭一个未知格；踩雷结束自己棋盘，另一方继续。','先比较是否通关，再比较安全已揭数，最后比较较少主动揭格。']){const li=document.createElement('li');li.textContent=text;$('rulesList').append(li)}
 $('rulesNote').textContent='经典竞速是独立评测模式。主项目仍研究共享棋盘上的资源争夺。C1为本地点击反馈模型，当前仅在9×9训练；它不是精确雷概率预测器。';
 $('provenance').textContent=`来源：${state.source} · 终局全雷显示已隔离，决策器只接收当方公共棋盘。`;$('replayControls').hidden=!replay;
}

async function reset(){await idle();busy=true;replay=null;cursor=[0,0];startedAt=null;elapsed=0;try{state=await api('/api/reset',{mode:$('mode').value,preset:$('difficulty').value,scoring:$('mode').value==='arena'?$('scoring').value:'diamonds',controllers:[$('p0').value,$('p1').value],source:new URLSearchParams(location.search).has('automation')?'browser_automation':'unverified_interaction'});syncSelectors();render()}catch(e){toast(e.message)}finally{busy=false}}
$('reset').onclick=reset;$('faceReset').onclick=reset;$('mode').onchange=()=>{populatePolicies($('mode').value);presetHint()};$('scoring').onchange=presetHint;$('difficulty').onchange=presetHint;$('watchBattle').onclick=()=>{const race=$('mode').value==='classic_race';$('mode').value=race?'classic_race':'arena';populatePolicies($('mode').value,race?['R1','C1']:['B3','L3']);if(!race&&!['legacy','beginner'].includes($('difficulty').value))$('scoring').value='survival-v1';reset()};$('pause').onclick=async()=>{await idle();await command('/api/pause',{paused:!state.paused})};$('step').onclick=async()=>{await idle();await command('/api/ai',{single:true})};$('heat').onchange=render;$('debug').onchange=render;$('speed').oninput=()=>$('speedValue').textContent=$('speed').value+' ms';
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>inputAction(b.dataset.action));document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||!state||replay)return;const a={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right',' ':'wait'}[e.key];if(a){e.preventDefault();inputAction(a)}else if(state.mode==='classic'&&e.key.toLowerCase()==='f'){e.preventDefault();command('/api/flag',{r:cursor[0],c:cursor[1]})}});
$('export').onclick=async()=>{try{const response=await fetch('/api/export');if(!response.ok)throw Error('导出失败');const raw=await response.text();exported=JSON.parse(raw);const a=document.createElement('a'),url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));a.href=url;a.download='arena-public-replay.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出公开观察回放。')}catch(e){toast(e.message)}};
function enterReplay(data){if(!data||typeof data!=='object')throw Error('回放格式不正确');if(['arena-public-replay-v1','arena-public-replay-v2','classic-race-public-replay-v3'].includes(data.replay?.schema))data=data.replay;if(['arena-public-replay-v1','arena-public-replay-v2'].includes(data.schema)){if(!Array.isArray(data.records))throw Error('回放记录无效');data={schema:'arena-ui-replay-1',mode:'arena',source:'automated_policy_replay',controllers:[0,1].map(i=>data.records.find(r=>r.actor===i)?.metadata?.policy||'unknown'),frames:[data.initial_observation,...data.records.map(r=>r.next_observation)],decisions:[null,...data.records.map(r=>({...r.metadata,actor:r.actor}))]}}if(data.schema==='classic-race-public-replay-v3'){if(!Array.isArray(data.records))throw Error('经典竞速记录无效');data={schema:'arena-ui-replay-1',mode:'classic_race',source:'automated_classic_race',controllers:[0,1].map(i=>data.records.find(r=>r.actor===i)?.metadata?.policy||'unknown'),frames:[data.initial_observation,...data.records.map(r=>r.next_observation)],decisions:[null,...data.records.map(r=>({...r.metadata,actor:r.actor}))]}}if(data.schema!=='arena-ui-replay-1'||!Array.isArray(data.frames)||!data.frames.length||data.frames.length>5000)throw Error('回放格式不正确');validateReplay(data);if(!data.decisions&&data.records?.records){const byRevision=new Map(data.records.records.map(r=>[r.next_observation?.revision,{...r.metadata,actor:r.actor}]));data.decisions=data.frames.map(f=>byRevision.get(f.revision)||null)}replay=data;$('replayRange').max=data.frames.length-1;$('replayRange').value=0;showFrame()}
function showFrame(){const i=Number($('replayRange').value);state={...state,observation:replay.frames[i],mode:replay.mode,controllers:replay.controllers,source:replay.source,decision:replay.decisions?.[i]||null,flags:replay.frames[i].ui_flags||[]};$('replayCounter').textContent=`状态 ${i} / ${replay.frames.length-1}`;syncSelectors();render()}
$('load').onclick=async()=>{await idle();try{if(!exported)throw Error('请先导出本局。');enterReplay(exported)}catch(e){toast(e.message)}};$('replayRange').oninput=showFrame;$('exitReplay').onclick=async()=>{replay=null;state=await api('/api/state');syncSelectors();render()};$('import').onchange=async e=>{await idle();try{const f=e.target.files[0];if(!f)return;if(f.size>100000000)throw Error('回放文件过大');enterReplay(JSON.parse(await f.text()))}catch(e){toast(e.message)}};
$('snapshot').onclick=async()=>{if(busy||replay)return;try{const j=await api('/api/snapshot',payload());snapshot=j.snapshot_id;$('restore').disabled=false;toast('局面保存在本地服务内存中。')}catch(e){toast(e.message)}};$('restore').onclick=()=>command('/api/restore',{snapshot_id:snapshot});
$('pasteReplay').onclick=async()=>{await idle();try{const text=$('replayText').value;if(text.length>100000000)throw Error('回放文件过大');enterReplay(JSON.parse(text));$('replayText').value=''}catch(e){toast(e.message)}};
async function tick(){if(state&&!busy&&!replay&&!state.paused&&['arena','classic_race'].includes(state.mode)&&!state.observation.done&&state.controllers[state.observation.turn]!=='human')await command('/api/ai');setTimeout(tick,Number($('speed').value))}
api('/api/state').then(s=>{state=s;syncSelectors();render();tick()}).catch(e=>toast(e.message));

setInterval(()=>{if(startedAt!==null&&state&&!state.observation.done&&!replay){elapsed=Math.floor((Date.now()-startedAt)/1000);if(state.mode==='classic')$('clockCounter').textContent=String(elapsed).padStart(3,'0')}},1000);
