'use strict';
const $=id=>document.getElementById(id);let state=null,busy=false,exported=null,replay=null,snapshot=null,cursor=[0,0],startedAt=null,elapsed=0;
const directions={up:[-1,0],down:[1,0],left:[0,-1],right:[0,1],wait:[0,0]};
function toast(s){$('toast').textContent=s;$('toast').hidden=false;setTimeout(()=>{$('toast').hidden=true},4000)}
async function api(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const j=await r.json();if(!r.ok)throw Error(j.error||r.status);return j}
function payload(extra={}){return{epoch:state.epoch,revision:state.observation.revision,...extra}}
function syncSelectors(){$('mode').value=state.mode;$('p0').value=state.controllers[0];$('p1').value=state.controllers[1];$('difficulty').value=state.observation.preset||'legacy';presetHint()}
function dimensions(o){return[o.height||o.size,o.width||o.size]}
function presetHint(){const p=$('difficulty').value,c=$('mode').value==='classic';$('presetHint').textContent=c?(p==='legacy'?'原始规则验证：首击可能踩雷。':'经典扫雷：首击安全、零区展开、插旗与数字连开。'):(p==='expert'?'挑战 v2 · 11 钻石 · 每人 3 次生命 · 最多 1600 步':p==='intermediate'?'挑战 v2 · 7 钻石 · 每人 3 次生命 · 最多 800 步':'原始实验 v1 · 3 钻石 · 每人 1 次生命 · 最多 200 步');}
function startClock(){if(startedAt===null&&!replay&&!state.observation.done)startedAt=Date.now()-elapsed*1000}
function chord(r,c){return command('/api/chord',{r,c})}
async function idle(){while(busy)await new Promise(resolve=>setTimeout(resolve,10))}
async function command(path,extra={}){if(busy||replay)return;busy=true;try{state=await api(path,payload(extra));if(path==='/api/restore')syncSelectors();render()}catch(e){toast(e.message)}finally{busy=false}}
function cellClick(r,c){if(!state||replay)return;let o=state.observation;if(state.mode==='classic'){cursor=[r,c];startClock();const n=o.revealed.find(x=>x[0]===r&&x[1]===c)?.[2];return n>0?chord(r,c):command('/api/action',{r,c})}const [pr,pc]=o.positions[o.turn];let a=Object.keys(directions).find(a=>directions[a][0]===r-pr&&directions[a][1]===c-pc);if(a)command('/api/action',{action:a});else toast('每次只能上下左右移动一格。')}
function inputAction(action){
 if(!state||replay)return;
 if(state.mode!=='classic')return command('/api/action',{action});
 if(action==='wait')return cellClick(...cursor);
 const [h,w]=dimensions(state.observation),[dr,dc]=directions[action];cursor=[Math.max(0,Math.min(h-1,cursor[0]+dr)),Math.max(0,Math.min(w-1,cursor[1]+dc))];render();
}
function render(){if(!state)return;const o=state.observation,classic=state.mode==='classic';$('board').replaceChildren();const revealed=new Map(o.revealed.map(x=>[x[0]+','+x[1],x[2]]));const diamonds=new Set((o.diamonds||[]).map(x=>x.join(','))), flags=new Set((classic?(o.flags||[]):state.flags||[]).map(x=>x.join(',')));const decision=state.decision;const [height,width]=dimensions(o);$('board').style.gridTemplateColumns=`repeat(${width},var(--cell))`;$('board').dataset.width=width;$('board').classList.toggle('expert',width>20);$('boardSize').textContent=`${width} × ${height}`;$('boardSpec').textContent=`${o.mine_count} 颗雷`+(classic?' · 揭开全部安全格':` · ${o.resource_count||3} 颗钻石 · 2 位玩家`);$('rulesBadge').textContent=o.rule_version;$('mineCounter').textContent=String(o.mine_count-flags.size).padStart(3,'0');$('clockLabel').textContent=classic?'秒 · 本地计时':'行动步数';$('clockCounter').textContent=String(classic?elapsed:o.steps).padStart(3,'0');$('faceReset').textContent=o.done?(o.winner==='win'?'☻':'☹'):'☺';if(o.done&&startedAt!==null){elapsed=Math.floor((Date.now()-startedAt)/1000);startedAt=null;}
for(let r=0;r<height;r++)for(let c=0;c<width;c++){const k=r+','+c,n=revealed.get(k),b=document.createElement('button');b.className='cell'+(n!==undefined?' revealed':'')+(diamonds.has(k)?' diamond':'')+(n===-1?' exploded':'');b.dataset.number=n;b.dataset.row=r;b.dataset.col=c;b.setAttribute('aria-label',`${r+1}行${c+1}列 ${n===-1?(classic?'地雷（终局揭示）':'已爆地雷'):n!==undefined?'数字'+n:diamonds.has(k)?'安全钻石':'未知'}`);let clue=document.createElement('span');clue.className='clue';clue.textContent=n===-1?'✹':diamonds.has(k)?'◆':n===undefined||n===0?'':n;b.append(clue);if(flags.has(k)){let f=document.createElement('span');f.className='flag';f.textContent='⚑';b.append(f)}if(!classic)o.positions.forEach((p,i)=>{if(p[0]===r&&p[1]===c){let pawn=document.createElement('span');pawn.className='pawn p'+i;pawn.textContent=(i?'B':'A')+(o.alive[i]?'':'×');b.append(pawn)}});if($('heat').checked&&decision?.risk&&n===undefined){let prob=decision.risk[r*o.size+c];if(Number.isFinite(prob)){let q=document.createElement('span');q.className='risk';q.textContent=Math.round(prob*100)+'%';b.append(q);b.style.boxShadow=`inset 0 0 18px rgba(200,85,50,${prob*.7})`}}b.onclick=()=>cellClick(r,c);b.oncontextmenu=e=>{e.preventDefault();command('/api/flag',{r,c})};b.ondblclick=e=>{if(classic){e.preventDefault();chord(r,c)}};if(classic&&r===cursor[0]&&c===cursor[1])b.classList.add('cursor');$('board').append(b)}
$('keyboardHint').textContent=classic?'方向键 / WASD 移动光标，空格揭格，F 插旗；左键揭格、右键插旗。点击已揭数字可连开（需相邻旗数匹配）。':'方向键 / WASD 移动，空格等待；也可点击相邻格。右键添加标记。';$('waitLabel').textContent=classic?'揭开光标格':'等待一回合';$('score0').textContent=classic?'—':o.scores[0];$('score1').textContent=classic?'—':o.scores[1];for(let i=0;i<2;i++)$('alive'+i).textContent=classic?'经典模式':o.alive[i]?(o.lives?`剩余 ${o.lives[i]} 次生命`:'可行动'):'已淘汰';$('turn').textContent=replay?'公开回放':o.done?'对局结束':classic?'经典扫雷':`轮到 ${o.turn?'B':'A'} · ${state.controllers[o.turn]}`;$('counter').textContent=classic?`${o.revealed.filter(x=>x[2]>=0).length} / ${height*width-o.mine_count} 安全格`:`${o.steps} / ${o.max_steps} 步`;
$('result').textContent=o.done?(classic?(o.won||o.winner==='win'?'全部安全格已揭开':'本局结束 · '+({mine:'踩雷',all_safe_revealed:'全部安全格已揭开'}[o.reason]||o.reason||o.winner||'踩雷')):(o.winner==='draw'?'平局':`玩家 ${o.winner===0?'A':'B'} 获胜`)+` · ${{diamonds_collected:'钻石取完',max_steps:'达到步数上限',all_eliminated:'双方停止行动',no_survivors:'双方均已淘汰'}[o.reason]||o.reason}`):state.paused?'已暂停 · 可用 AI 单步观察':classic?(o.first_click_safe?'左键揭格 · 右键插旗 · 首击安全':'原版验证规则 · 首击可能踩雷'):'先到钻石格得分 · 未知雷位保持隐藏';$('pause').textContent=state.paused?'继续':'暂停';$('diagnosis').hidden=!$('debug').checked;
$('diagnosis').replaceChildren();if(decision){const p=document.createElement('p');p.textContent=`${decision.policy} → ${decision.action} · ${decision.risk_status}`;$('diagnosis').append(p);const t=document.createElement('p');t.textContent=decision.target?`${decision.diagnostics?.target_kind?.startsWith('inferred_')?'动作推断目标（不是独立目标输出）':'规则策略明确目标'}：(${decision.target[0]+1}, ${decision.target[1]+1})。`:'此策略未显式输出目标。';$('diagnosis').append(t);const pre=document.createElement('pre');pre.textContent=JSON.stringify(decision.diagnostics||{},null,2);$('diagnosis').append(pre)}else $('diagnosis').textContent='AI 行动后显示其实际输出。热图对应最近一次决策前的公开状态。';$('rulesList').replaceChildren();const rules=classic?['揭开所有没有地雷的格子即可获胜。','右键插旗；数字表示周围八格的地雷数。','相邻旗数等于数字时，点击数字连开；插错旗会踩雷。']:[`上下左右移动一格，或等待；钻石先到先得，共 ${o.resource_count||3} 颗。`,o.lives?'踩雷扣一次生命并返回自己的起点；生命耗尽才停止行动。':'踩雷后停止行动，保留得分；另一方继续。',`钻石取完、双方淘汰或满 ${o.max_steps} 步结束。只比钻石数，同分平局。`];for(const text of rules){const li=document.createElement('li');li.textContent=text;$('rulesList').append(li)}$('rulesNote').textContent=classic?(o.first_click_safe?'经典模式首次揭格后才布雷，首击周围保证安全，零区自动展开。专家 30×16 / 99 雷，不保证每张图都无需猜测。':'原始经典验证模式固定雷位，首击不保证安全。'):(o.lives?'挑战规则 v2：两角 3×3 起点区与钻石公开安全；零区展开。生命、复活和钻石争夺为本项目新增规则，与经典扫雷区分。':'原始实验 v1：起点与钻石保证安全，不展开零区，一次踩雷即淘汰。历史评测仅适用于此版本。');$('provenance').textContent=`来源：${state.source} · 公开观察，无隐藏雷图。`;$('replayControls').hidden=!replay;
}
async function reset(){await idle();busy=true;replay=null;cursor=[0,0];startedAt=null;elapsed=0;try{state=await api('/api/reset',{mode:$('mode').value,preset:$('difficulty').value,controllers:[$('p0').value,$('p1').value],source:new URLSearchParams(location.search).has('automation')?'browser_automation':'unverified_interaction'});syncSelectors();render()}catch(e){toast(e.message)}finally{busy=false}}
$('reset').onclick=reset;$('faceReset').onclick=reset;$('mode').onchange=presetHint;$('difficulty').onchange=presetHint;$('watchBattle').onclick=()=>{$('mode').value='arena';$('p0').value='B1';$('p1').value='B2';reset()};$('pause').onclick=async()=>{await idle();await command('/api/pause',{paused:!state.paused})};$('step').onclick=async()=>{await idle();await command('/api/ai',{single:true})};$('heat').onchange=render;$('debug').onchange=render;$('speed').oninput=()=>$('speedValue').textContent=$('speed').value+' ms';
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>inputAction(b.dataset.action));document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||!state||replay)return;const a={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right',' ':'wait'}[e.key];if(a){e.preventDefault();inputAction(a)}else if(state.mode==='classic'&&e.key.toLowerCase()==='f'){e.preventDefault();command('/api/flag',{r:cursor[0],c:cursor[1]})}});
$('export').onclick=async()=>{try{const response=await fetch('/api/export');if(!response.ok)throw Error('导出失败');const raw=await response.text();exported=JSON.parse(raw);const a=document.createElement('a'),url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));a.href=url;a.download='arena-public-replay.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出公开观察回放。')}catch(e){toast(e.message)}};
function enterReplay(data){if(!data||typeof data!=='object')throw Error('回放格式不正确');if(['arena-public-replay-v1','arena-public-replay-v2'].includes(data.replay?.schema))data=data.replay;if(['arena-public-replay-v1','arena-public-replay-v2'].includes(data.schema)){if(!Array.isArray(data.records))throw Error('回放记录无效');data={schema:'arena-ui-replay-1',mode:'arena',source:'automated_policy_replay',controllers:[0,1].map(i=>data.records.find(r=>r.actor===i)?.metadata?.policy||'unknown'),frames:[data.initial_observation,...data.records.map(r=>r.next_observation)],decisions:[null,...data.records.map(r=>r.metadata)]}}if(data.schema!=='arena-ui-replay-1'||!Array.isArray(data.frames)||!data.frames.length||data.frames.length>5000)throw Error('回放格式不正确');validateReplay(data);if(!data.decisions&&data.records?.records){const byRevision=new Map(data.records.records.map(r=>[r.next_observation?.revision,r.metadata]));data.decisions=data.frames.map(f=>byRevision.get(f.revision)||null)}replay=data;$('replayRange').max=data.frames.length-1;$('replayRange').value=0;showFrame()}
function showFrame(){const i=Number($('replayRange').value);state={...state,observation:replay.frames[i],mode:replay.mode,controllers:replay.controllers,source:replay.source,decision:replay.decisions?.[i]||null,flags:replay.frames[i].ui_flags||[]};$('replayCounter').textContent=`状态 ${i} / ${replay.frames.length-1}`;syncSelectors();render()}
$('load').onclick=async()=>{await idle();try{if(!exported)throw Error('请先导出本局。');enterReplay(exported)}catch(e){toast(e.message)}};$('replayRange').oninput=showFrame;$('exitReplay').onclick=async()=>{replay=null;state=await api('/api/state');syncSelectors();render()};$('import').onchange=async e=>{await idle();try{const f=e.target.files[0];if(!f)return;if(f.size>100000000)throw Error('回放文件过大');enterReplay(JSON.parse(await f.text()))}catch(e){toast(e.message)}};
$('snapshot').onclick=async()=>{if(busy||replay)return;try{const j=await api('/api/snapshot',payload());snapshot=j.snapshot_id;$('restore').disabled=false;toast('局面保存在本地服务内存中。')}catch(e){toast(e.message)}};$('restore').onclick=()=>command('/api/restore',{snapshot_id:snapshot});
$('pasteReplay').onclick=async()=>{await idle();try{const text=$('replayText').value;if(text.length>100000000)throw Error('回放文件过大');enterReplay(JSON.parse(text));$('replayText').value=''}catch(e){toast(e.message)}};
async function tick(){if(state&&!busy&&!replay&&!state.paused&&state.mode==='arena'&&!state.observation.done&&state.controllers[state.observation.turn]!=='human')await command('/api/ai');setTimeout(tick,Number($('speed').value))}
api('/api/state').then(s=>{state=s;syncSelectors();render();tick()}).catch(e=>toast(e.message));

setInterval(()=>{if(startedAt!==null&&state&&!state.observation.done&&!replay){elapsed=Math.floor((Date.now()-startedAt)/1000);if(state.mode==='classic')$('clockCounter').textContent=String(elapsed).padStart(3,'0')}},1000);
